export interface Quotation {
    quotAuthorisedBy?: string,
    quotAuthorisedDt?: Date,
    quotAgntAgentCode?: number,
    quotBrnCode?: number,
    quotBranch?: String,
    quotCancelReason?: string,
    quotClntCode?: number,
    quotClntType?: string,
    quotCode?: number,
    quotCommAmt?: number,
    quotConfirmed?: string,
    quotConfirmedBy?: string,
    quotConfirmedDt?: Date,
    quotCoverFrom?: Date,
    quotCoverTo?: Date,
    quotCurCode?: number,
    quotCurSymbol?: string,
    quotDate?: Date,
    quotExpiryDate?: Date,
    quotPaymentFrequency?: string,
    quotNo?: String,
    quotPremium?: number,
    quotPreparedBy?: string,
    quotPreparedDt?: Date,
    quotReadyBy?: string,
    quotReadyDate?: Date,
    quotRevised?: string,
    quotStatus?: string,
    quotTotPropertyVal?: number
}

