export interface QuoteProduct {
    qpCode?: number,
    qpProCode?: number,
    qpProShtDesc?: String,
    qpWefDate?: Date,
    qpWetDate?: Date,
    qpQuotCode?: number,
    qpQuotNo?: String,
    qpQuotRevisionNo?: String,
    qpTotalSi?: number,
    qpPremium?: number,
    qpComm?: number,
    qpRemarks?: String,
    qpFap?: number,
    qpStatus?: String,
    qpBinder?: String,
    qpBindCode?: number,
    qpSubCommAmt?: number,
    qpConverted?: String

    // id?: string,
    // code?: number,
    // name?: string,
    // description?: string,
    // productCode?: number,
    // coverFrom?: string,
    // coverTo?: string,
    // quoteCode?: number,
    // quoteNo?: string,
    // totalSumInsured?: number,
    // premium?: number,
    // futureAnnualPremium?: number,
}