export interface QuoteRiskLimit {
    qrlCode?: number,
    qrlIpuCode?: number,
    qrlSectCode?: number,
    qrlSectShtDesc?: String,
    qrlRowNum?: number,
    qrlCalcGroup?: number,
    qrlLimitAmt?: number,
    qrlPremRate?: number,
    qrlPremAmt?: number,
    qrlRateType?: String,
    qrlRateDesc?: String,
    qrlSectType?: String,
    qrlSectExcessDetail?: String,
    qrlOriginalPremRate?: number,
    qrlRateChangeRemarks?: String,
    qrlChangeDoneBy?: String,
    qrlMinPremium?: number,
    qrlComment?: String,
    qrlMultiplierRate?: number,
    qrlMultiplierDivFactor?: number,
    qrlAnnualPremium?: number,
    qrlRateDivFact?: number,
    qrlDesc?: String,
    qrlUsedLimit?: number,
    qrlCompute?: number,
    qrlIndemPrd?: number,
    qrlPrdType?: String,
    qrlIndemFstprd?: number,
    qrlIndemFstprdPcd?: number,
    qrlIndemRemprdPct?: number,
    qrlDualBasis?: String,
    qrlPremAccumulation?: number,
    qrlPremProrata?: number,
    qrlPrevPrem?: number,
    qrlDeclarationSection?: String,
    qrlPrevLimit?: number,
    qrlActualPrem?: number,
    qrlPrevPremProrata?: number,
    qrlAnnualActualPrem?: number,
    qrlEmlPct?: number,
    qrlTopLocRate?: number,
    qrlTopLocDivFact?: number,
    qrlFreeLimitAmt?: number,
    qrlLimitPrd?: number,
    qrlActualRatePrem?: number,
    qrlPrevEndrPremRate?: number,
    qrlPrevEndrRateDivFact?: number,
    qrlPrevEndrMultRate?: number,
    qrlPrevEndrMultDivFact?: number,
    qrlExpired?: String,
    qrlFreeLimit?: number,
    qrlProrataFull?: String,
    qrlSiLimitType?: String,
    qrlSiRate?: number,
    qrlCoverType?: String,
    qrlPrrMaxRate?: number,
    qrlPrrMinRate?: number,
    qrlFirstLoss?: String,
    qrlFirstLossAmtPcnt?: String, 
    qrlFirstLossValue?: number,
    qrlIsEditable?: number,
    qrlRateDivFactor?: number,
    qrlQrCode?: number

    // id?: string,
    // code?: number,
    // quoteCode?: number,
    // quoteRiskCode?: number,
    // sectionCode?: number,
    // limitAmount?: number,
    // premiumRate?: number,
    // premiumAmount?: number,
    // commissionAmount?: number,
    // rateDivisionFactor?: number,
    // riskSectionCode?: number,
}