export interface QuoteRisk {
    id?: string,
    code?: number,
    name?: string,
    quoteCode?: number,
    quoteRiskCode?: number,
    quoteNo?: string,
    riskId?: string,
    riskDescription?: string,
    value?: string,
    subclassCode?: number,
    quoteProductCode?: number,
    coverTypeCode?: number,
    premium?: number,
    coverFrom?: string,
    coverTo?: string,
    clientCode?: number,
    clientType?: string,
    annualPremium?: number,
}