export interface Quotation {
    // id?: string,
    // code?: number,
    // quoteNo?: number,
    // client?: any,
    // clientCode?: number, // remove client code and client name
    // clientName?: string,
    // clientEmail?: string,
    // clientPhone?: string,
    // agent?: any, 
    // agentCode?: number, // remove agentCode and agentName
    // // agentName?: string,
    // // sourceCode?: number,
    // // branchCode?: number,
    // source?: string,
    // branch?: string,
    // currency?: any,
    // // currencyCode?: number,
    // // currecnySymbol?: string,
    // coverFrom?: string,
    // coverTo?: string,
    // paymentFrequency?: string,
    // totalPropertyValue?: number,
    // status?: string,
    // expiryDate?: string,
    // ok?: string,
    // premium?: number,
    // commissionAmount?: number,
    // // clientType?: string,

    quotAuthorisedBy?: string,
    quotAuthorisedDt?: Date,
    quotBrnCode?: number,
    quotCancelReason?: string,
    quotClntCode?: number,
    quotClntType?: string,
    quotCode?: number,
    quotCommAmt?: number,
    quotConfirmed?: string,
    quotConfirmedBy?: string,
    quotConfirmedDt?: Date,
    quotCoverFrom?: Date,
    quotCoverTo?: Date,
    quotCurCode?: number,
    quotCurSymbol?: string,
    quotDate?: Date,
    quotExpiryDate?: Date,
    quotFreqOfPayment?: string,
    quotNo?: number,
    quotPremium?: number,
    quotPreparedBy?: string,
    quotPreparedDt?: Date,
    quotReadyBy?: string,
    quotReadyDate?: Date,
    quotRevised?: string,
    quotStatus?: string,
    quotTotPropertyVal?: number
}

